import LeftSideLayout from '@/components/home/LeftSideLayout'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='m-0 p-0 w-[100vw] h-[100vh] border flex'>
        <LeftSideLayout></LeftSideLayout>
        {children}
        </body>
    </html>
  )
}
