import LeftSideLayout from '@/components/home/LeftSideLayout'
import './globals.css'
import type { Metadata } from 'next'
import { twMerge } from 'tailwind-merge'
import { myFont3 } from '@/components/Font/fonts'
import dynamic from 'next/dynamic'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const SearchDialog = dynamic(() => import('../components/home/SearchDialog'), { ssr: false })
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={twMerge(myFont3.className,`m-0 p-0 w-[100dvw]  flex overflow-x-hidden`)} >
      
      <LeftSideLayout />
      <SearchDialog />
        {children}
        </body>
    </html>
  )
}
