import LeftSideLayout from '@/components/home/LeftSideLayout'
import './globals.css'
import type { Metadata } from 'next'
import { twMerge } from 'tailwind-merge'
import { myFont3 } from '@/components/Font/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={twMerge(myFont3.className,`m-0 p-0 w-[100dvw] border flex overflow-x-hidden`)} >
      <LeftSideLayout />
        {children}
        </body>
    </html>
  )
}
